### ISSUE TITLE
No module named Raiblocks

### ISSUE THREAD

**Issue by Afkbio** [dourvaris/raiblocks-python#1]
Hello :)

Tried to pip install raiblocks-py on win64 with python 3.6 32bits
pip install raiblocks worked well:
`pip install raiblocks`
`Installing collected packages: chardet, urllib3, idna, certifi, requests, raiblocks`
`Successfully installed certifi-2017.11.5 chardet-3.0.4 idna-2.6 raiblocks-0.0.0 requests-2.18.4 urllib3-1.22`

But then I get this: 
`from raiblocks import RPCClient`
`ModuleNotFoundError: No module named 'raiblocks'`

Any idea what went wrong ?

**Comment by dourvaris** [comment]
Not sure but  `raiblocks-0.0.0` was downloaded which is not the right version - should be 1.0.0rc3 at the moment. Unfortunately I don't have a windows machine to test myself

**Comment by dourvaris** [comment]
Found the problem - pypi doesn't expose the rc versions - I've tagged and uploaded 1.0.0 - it should work now.

**Comment by Afkbio** [comment]
No problem, thank you
