### ISSUE TITLE
accounts_pending method doesn't handle null response gracefully

### ISSUE THREAD

**Issue by jnmclarty** [dourvaris/raiblocks-python#4]
Hi,

I'm kicking the tires on this promising library.  Arriving at the issue below might be user error.  Even if it is, a smarter error message might make sense.  

# Current Error
``` python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-a1fdb35d80ab> in <module>()
----> 1 rpc.accounts_pending(accounts=account_list)

d:\Anaconda3-4.1.1-64\envs\rai\lib\site-packages\raiblocks\rpc.py in accounts_pending(self, accounts, count, threshold, source)
    588                 continue
    589
--> 591             for key, value in data.items():
    592                 if isinstance(value, six.string_types):  # amount
    593                     data[key] = int(value)

AttributeError: 'str' object has no attribute 'items'
````

# How to Reproduce
``` python
from raiblocks import RPCClient
rpc = RPCClient('http://localhost:7076')
rpc.version()

wallet = rpc.wallet_create()
account = rpc.account_create(wallet=wallet)
account_list = rpc.account_list(wallet=wallet)
rpc.accounts_pending(accounts=account_list)
```

Looks like the rpc.py is receiving...

``` json
{'blocks': {'xrb_3wuy5ba4ahskjn36g4nnmgdio9frkoq158uykiropja7fm78zuynw11azc5k': ''}}
```
on line 583

So, it just needs to handle the blank.

If somebody could confirm a logical error message.  "Eg, need to call method ______ " before requesting pending accounts." I could send a PR.  I'm just learning the Raiblocks object model...and I'm not quite sure if I need to open a block manually or what...still learning here.

I'm using Python 3.6.0 on Windows 10.

**Comment by dourvaris** [comment]
Thanks for the bug report - the RPC server returns empty strings instead of empty lists in this case and the client wasn't handling that correctly - has been fixed in ba94f73.
