### ISSUE TITLE
RPCClient constructor gives no indication on failed connection

### ISSUE THREAD

**Issue by pramttl** [dourvaris/raiblocks-python#6]
The following call always returns successfully whether or not there is an error establishing a connection:

    rpc = RPCClient('http://localhost:7076')

Only when I run `rpc.version()`, I realize whether the connection fails or not.

### Steps to Reproduce

Run the library without a a local Rai server/node (or an improperly configured server/node)

### Expected Behavior

The constructor should itself fail if a connection cannot be established throwing a Connection error/exception.

**Comment by JamesBingo** [comment]
@dourvaris  What about trying a call to version inside the `RPCClient` constructor and printing success/fail message. I can create a pull request if you agree?

**Comment by dourvaris** [comment]
Most libraries I've seen don't make a backend call upon instantiation - it's probably a better idea to let the user decide if the call is made and how to handle it

```
try:
    rpc = RPCClient()
    rpc.version()
except RPCException:
    # handle it
```

**Comment by JamesBingo** [comment]
Yer I had a look at some other libraries and I agree.
